# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
linters:
  default: fast
  enable:
    - staticcheck
    - govet
    - errcheck
    - revive
    - misspell
    - unparam
    - unused
    - ineffassign
  
  disable:
    - wsl
    - godot
    - mnd
    - exhaustruct
    - depguard
    - ireturn

formatters:
  enable:
    - gofmt

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 5
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 1
