name: Notify Telegram

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: [self-hosted]
    steps:
      - name: Send Telegram Message
        run: |
          MSG="🛎️ New ${{ github.event_name }}: [${{ github.event.title }}](${{ github.event.html_url }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$MSG" \
            -d parse_mode="Markdown"
